### ISSUE TITLE
New creation of adapters via portal do not work

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/dev-portal#53]
![IMAGE 2022-01-09 19:15:04](https://user-images.githubusercontent.com/11976694/148694964-63bd5bad-97e1-455e-afa0-e9f3c086eebd.jpg)

**Comment by Apollon77** [comment]
[ioBroker.homekit-td.zip](https://github.com/ioBroker/dev-portal/files/7835645/ioBroker.homekit-td.zip)

This is the Zip file

**Comment by UncleSamSwiss** [comment]
Thanks for your report!

It is now fixed - we needed to add the "workflows" scope to the authentication.
