### ISSUE TITLE
Allow addition of dev-server when creating adapter

### ISSUE THREAD

**Issue by Apollon77** [ioBroker/dev-portal#54]

**Comment by UncleSamSwiss** [comment]
Dev-server is purely on the developer machine. It has no impact on the GitHub repository and thus there is no way to "add" the dev-server while creating an adapter online. Like calling "nom install", setting up dev-server must be done locally by the developer **after** creating it with the portal.

**Comment by UncleSamSwiss** [comment]
The dev dependency is a good idea (I had the same issue on my Ubuntu laptop), please create an issue in the creator and describe exactly what would be required (we would probably have to add it to the scripts as well). 

Ignore files are adjusted by dev-server if needed and thanks to the npm whitelist, this is already covered by the creator by default (yes, .gitignore just be adjusted).

**Comment by Apollon77** [comment]
https://github.com/ioBroker/create-adapter/issues/864
