### ISSUE TITLE
Adapter-check: make ## License check more tolerant

### ISSUE THREAD

**Issue by mcm1957** [ioBroker/dev-portal#61]
snmp Adapter does not pass the adapter check
       [E604] No "## License" found in README.md

The reason is, that this header is bolded (just as all othe rlevel 2 headers) within this README.md

        ## __License__

So please consider accepti ng ## License as well as ## __License__

The reason to mark the headers bold is that this provides a better readabilty - at least in my oppinion.

**Comment by UncleSamSwiss** [comment]
This issue is related to the Adapter Checker which is an external service used by the portal and it's NOT part of the portal.

The code for the Adapter Checker can be found here: https://github.com/ioBroker/ioBroker.repochecker

Please open an issue there.

**Comment by mcm1957** [comment]
https://github.com/ioBroker/ioBroker.repochecker/issues/68

**Comment by Apollon77** [comment]
@mcm1957 The other question is ... why you do that? the two hashes already state "show it as Heading-2-format ... why it is made bold additzionally ... I would more remove this unneeded formatting :-)

**Comment by mcm1957** [comment]
@Apollon77 
I did it as in my oppinion the readability is better.
But I will give it a second check.
