### ISSUE TITLE
Adapter Check does not work 

### ISSUE THREAD

**Issue by xXBJXx** [ioBroker/dev-portal#65]
![image](https://user-images.githubusercontent.com/32600934/209432282-feaa1037-cdef-430a-a71f-fe85719f6f20.png)
I have tried it with different adapters, it always comes back the same error in https://adapter-check.iobroker.in/ the check works.
I have looked at the URL, it seems to be sent a different one 
![image](https://user-images.githubusercontent.com/32600934/209432414-8e9aca12-3062-4337-8357-ab9f46eea045.png)

adapter-check.iobroker.in ⇨ https://e7tj1cpjna.execute-api.eu-west-1.amazonaws.com/?url=https%3A%2F%2Fgithub.com%2FxXBJXx%2FioBroker.hue-sync-box&branch=main

iobroker.dev ⇨ https://3jjxddo33l.execute-api.eu-west-1.amazonaws.com/default/checkAdapter?url=https%3A%2F%2Fgithub.com%2FxXBJXx%2FioBroker.hue-sync-box

**Comment by xXBJXx** [comment]
fixed in commit https://github.com/ioBroker/dev-portal/commit/2fef783357533ec4b2537b89d004801bd73b64fd

**Comment by Apollon77** [comment]
Ja aber geht es schon? Ich muss noch releasen

**Comment by xXBJXx** [comment]
hab es probiert es geht 
![image](https://user-images.githubusercontent.com/32600934/213944310-c530c666-6db8-4bcf-a88f-68df607efe0f.png)

**Comment by Apollon77** [comment]
aahh stimmt release ist automatisch ... :-) Getestet... geht
